// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Eatery struct {
	ID string `json:"id"`
	// Name of eatery
	Name string `json:"name"`
	// A number from 1 - 5 with 1 being lowest and 5 being highest (from Yelp)
	Rating *float64 `json:"rating"`
	// The location of the eatery
	Location *Location `json:"location"`
}
