// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Location struct {
	// hack concatenation of lat & long
	ID string `json:"id"`
	// The latitude of the location
	Latitude *float64 `json:"latitude"`
	// The longitude of the location
	Longitude *float64 `json:"longitude"`
	// The label of the location
	Label *string `json:"label"`
	// The locality of the location
	Locality *string `json:"locality"`
	// The county of the location
	County *string `json:"county"`
	// The continent of the location
	Continent *string `json:"continent"`
}

func (Location) IsEntity() {}
